"use client";
import {useCallback,useEffect,useState} from "react";
import {useParams} from "next/navigation";
import Link from "next/link";
import {apiRequest} from "@/lib/api";
export default function Campanha(){
 const {id}=useParams();const [m,setM]=useState(null),[resgates,setR]=useState([]),[erro,setErro]=useState(""),[inicio,setInicio]=useState(""),[fim,setFim]=useState(""),[periodo,setPeriodo]=useState({inicio:"",fim:""}),[busy,setBusy]=useState(false);
 const buscarDados=useCallback(async(inicioSelecionado,fimSelecionado)=>{const q=new URLSearchParams();if(inicioSelecionado)q.set("inicio",inicioSelecionado+"T00:00:00-03:00");if(fimSelecionado)q.set("fim",fimSelecionado+"T23:59:59-03:00");const [metricas,lista]=await Promise.all([apiRequest("/campanhas/"+id+"/metricas?"+q,{forceRefresh:true}),apiRequest("/campanhas/"+id+"/resgates",{forceRefresh:true})]);return {metricas,resgates:lista.resgates};},[id]);
 async function carregar(){try{const dados=await buscarDados(periodo.inicio,periodo.fim);setM(dados.metricas);setR(dados.resgates);}catch(e){setErro(e.message);}}
 useEffect(()=>{let ativo=true;if(id)buscarDados(periodo.inicio,periodo.fim).then(dados=>{if(ativo){setM(dados.metricas);setR(dados.resgates);}}).catch(e=>{if(ativo)setErro(e.message);});return()=>{ativo=false;};},[id,periodo,buscarDados]);
 async function entregar(r){setBusy(true);try{await apiRequest("/campanhas/resgates/"+r.id_resgate+"/entregar",{method:"POST"});await carregar();}catch(e){setErro(e.message);}finally{setBusy(false);}}
 return <main className="mx-auto max-w-5xl p-6"><Link href="/restaurante/campanhas">Voltar às campanhas</Link><h1 className="my-5 text-3xl">Resultados e entregas</h1>{erro&&<p role="alert">{erro}</p>}
 <form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();setPeriodo({inicio,fim});}}><label>De<input type="date" value={inicio} onChange={e=>setInicio(e.target.value)}/></label><label>Até<input type="date" value={fim} onChange={e=>setFim(e.target.value)}/></label><button>Filtrar resultados</button></form>
 {m&&<><p className="mt-5 text-sm">Período: {new Date(m.periodo.inicio).toLocaleString("pt-BR")} a {new Date(m.periodo.fim).toLocaleString("pt-BR")}. Eventos são deduplicados por cliente, campanha, tipo e dia de Brasília; contagens únicas são clientes distintos no período. Os índices de eventos são razões agregadas no período, não conversões atribuídas a uma mesma sessão.</p><div className="my-6 grid gap-3 sm:grid-cols-3">{[["Visualizações registradas",m.visualizacoes],["Clientes que visualizaram",m.visualizacoes_unicas],["Cliques registrados",m.cliques],["Clientes que clicaram",m.cliques_unicos],["Reservas iniciadas",m.reservas_iniciadas],["Resgates válidos",m.resgates_validos],["Resgates cancelados",m.resgates_cancelados],["Resgates com pedido",m.resgates_com_pedido],["Benefícios entregues",m.beneficios_entregues],["Pedidos pagos atribuídos",m.pedidos_pagos],["Pagamentos antes de reembolsos","R$ "+m.receita_bruta_atribuida.toFixed(2)],["Reembolsos atribuídos","R$ "+m.reembolsos_atribuidos.toFixed(2)],["Pagamentos após reembolsos","R$ "+m.receita_liquida_atribuida.toFixed(2)],["Descontos registrados","R$ "+m.descontos_registrados.toFixed(2)],["Cliques / visualizações",(m.indice_cliques_por_visualizacao*100).toFixed(1)+"%"],["Reservas iniciadas / cliques",(m.indice_reservas_iniciadas_por_clique*100).toFixed(1)+"%"],["Pedidos pagos / resgates com pedido",(m.taxa_pedido_pago_por_resgate_com_pedido*100).toFixed(1)+"%"]].map(([t,v])=><article className="rounded-xl border p-4" key={t}><h2>{t}</h2><strong>{v}</strong></article>)}</div><p>Valores financeiros vêm do estado atual dos pagamentos dos pedidos com resgate da campanha no período. Pagamentos antes de reembolsos já consideram o benefício aplicado ao pedido; não representam receita contábil, lucro nem crescimento incremental. Descontos registrados não incluem custo de itens gratuitos.</p>{m.historico_limitado&&<p role="status">Parte do histórico não permite deduplicação ou reconstrução financeira completa; compare esses números com cautela.</p>}</>}
 <h2 className="my-5 text-2xl">Benefícios reservados</h2>{resgates.map(r=><article key={r.id_resgate} className="my-3 rounded-xl border p-4"><h3>Reserva #{r.id_reserva} · {r.status.toLowerCase()}</h3><p>{r.condicoes?.titulo??"Condições históricas não disponíveis"}</p>{r.condicoes?.itens_oferecidos?.map(i=><p key={i.id_produto}>{i.quantidade} × {i.nome}</p>)}<p>Desconto: R$ {Number(r.valor_beneficio).toFixed(2)}</p>{r.entregue_em?<p>Entrega confirmada em {new Date(r.entregue_em).toLocaleString("pt-BR")}</p>:r.status!=="CANCELADO"&&<button disabled={busy} onClick={()=>entregar(r)}>Confirmar entrega após check-in</button>}</article>)}</main>;
}
