"use client";

import {
  AlertTriangle,
  Armchair,
  ArrowLeft,
  ArrowRight,
  Banknote,
  Bell,
  Camera,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronRight,
  Clock3,
  Download,
  FileText,
  Headphones,
  LogOut,
  LayoutGrid,
  Menu,
  MapPin,
  MessageSquare,
  Pencil,
  Plus,
  Printer,
  Receipt,
  Search,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Star,
  Store,
  Sun,
  Trash2,
  UserRoundPlus,
  UtensilsCrossed,
} from "lucide-react";

const icons = {
  alert: AlertTriangle,
  appearance: Sun,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  calendar: CalendarDays,
  camera: Camera,
  category: LayoutGrid,
  check: Check,
  chevron: ChevronDown,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  clock: Clock3,
  download: Download,
  file: FileText,
  filter: SlidersHorizontal,
  menu: Menu,
  "log-out": LogOut,
  "map-pin": MapPin,
  message: MessageSquare,
  money: Banknote,
  orders: UtensilsCrossed,
  pencil: Pencil,
  plus: Plus,
  print: Printer,
  receipt: Receipt,
  search: Search,
  seat: Armchair,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  smile: Smile,
  star: Star,
  store: Store,
  support: Headphones,
  trash: Trash2,
  user: UserRoundPlus,
  utensils: UtensilsCrossed,
};

export function RestaurantIcon({ type, className = "h-5 w-5" }) {
  const Icon = icons[type] ?? FileText;
  return <Icon className={className} aria-hidden="true" />;
}
