"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {apiRequest} from "@/lib/api";
import {enviarImagemCardapio} from "@/lib/imagem-cardapio";
import {FormStepper} from "@/components/ui/form-stepper";
import {FormStepActions} from "@/components/ui/form-step-actions";
const novo=()=>({titulo:"",descricao:"",tipo_beneficio:"DESCONTO_PERCENTUAL",valor_beneficio:5,preco_combo:"",inicio_em:"",fim_em:"",limite_usos:10,minimo_pessoas:"",minimo_itens:"",produtos:[],beneficio_itens:[],regras:"",imagem_url:"",status:"RASCUNHO"});
const tipos=["DESCONTO_PERCENTUAL","DESCONTO_FIXO","ITEM_CORTESIA","BEBIDA","ENTRADA","SOBREMESA","COMBO"];
const label=s=>s.replaceAll("_"," ").toLowerCase();
const motivoEstado=c=>c.precisa_configuracao?"Novos resgates bloqueados até configurar o benefício.":c.status==="RASCUNHO"?"Ainda não foi publicada.":c.status==="AGENDADA"?`Começa em ${new Date(c.inicio_em).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}.`:c.status==="ATIVA"?`Disponível até ${new Date(c.fim_em).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}, enquanto houver usos.`:c.status==="PAUSADA"?"Pausada pelo restaurante; não aparece para novos clientes.":c.status==="ESGOTADA"?"O limite de usos foi atingido.":c.status==="EXPIRADA"?"O prazo terminou.":c.status==="ENCERRADA"?"Encerrada pelo restaurante.":"";
const dataCampanha=data=>new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Sao_Paulo",day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(data)).replace(".","");
const classeStatus=status=>status==="ATIVA"?"bg-emerald-50 text-emerald-800":status==="AGENDADA"?"bg-app-creme-leve text-app-caramelo-torrado":status==="PAUSADA"?"bg-stone-100 text-stone-700":"bg-stone-100 text-app-cinza";
const local=d=>d?new Intl.DateTimeFormat("sv-SE",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(d)).replace(" ","T"):"";
const classe="w-full rounded-lg border border-app-baunilha-dourada bg-white p-3";
const normalizarTexto=valor=>String(valor??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
export default function CampanhasPage(){
 const [dados,setDados]=useState({campanhas:[],produtos:[]}),[form,setForm]=useState(novo),[erro,setErro]=useState(""),[busy,setBusy]=useState(false),[sugestoes,setSugestoes]=useState([]),[analise,setAnalise]=useState(null),[motivoSemSugestao,setMotivoSemSugestao]=useState(""),[erroSug,setErroSug]=useState(""),[estadoAcesso,setEstadoAcesso]=useState("carregando"),[estadoSugestoes,setEstadoSugestoes]=useState("carregando"),[preview,setPreview]=useState(false),[nomeImagem,setNomeImagem]=useState(""),[buscaElegiveis,setBuscaElegiveis]=useState(""),[buscaBeneficios,setBuscaBeneficios]=useState(""),[etapaAtual,setEtapaAtual]=useState(0);
 const carregar=async(opcoes={})=>{try{const resposta=await apiRequest("/campanhas",{forceRefresh:true,...opcoes});setDados(resposta);setEstadoAcesso("liberado");return resposta;}catch(e){if(opcoes.signal?.aborted||e?.name==="AbortError"||/signal is aborted/i.test(String(e?.message)))return null;if(e.code==="PROFESSIONAL_PLAN_REQUIRED"){setEstadoAcesso("bloqueado");return null;}setEstadoAcesso("erro");setErro(e.message);return null;}};
 useEffect(()=>{const controller=new AbortController();let expirou=false;const timeout=window.setTimeout(()=>{expirou=true;controller.abort();},10000);(async()=>{const campanhas=await carregar({signal:controller.signal});if(!campanhas)return;try{const d=await apiRequest("/campanhas/sugestoes",{forceRefresh:true,signal:controller.signal});const items=d.sugestoes??[];setSugestoes(items);setAnalise(d.analise??null);setMotivoSemSugestao(d.motivo_sem_sugestao??"");setEstadoSugestoes(items.length||d.analise?.disponivel?"com_dados":"vazio");}catch(e){if(e?.name!=="AbortError"||expirou){setErroSug(expirou?"As sugestões demoraram demais para carregar. Tente novamente.":e.message);setEstadoSugestoes("erro");}}finally{window.clearTimeout(timeout);}})();return()=>{window.clearTimeout(timeout);controller.abort();};},[]);
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const editar=c=>{setForm({...novo(),...c,inicio_em:local(c.inicio_em),fim_em:local(c.fim_em),produtos:c.produtos??c.campanhas_inteligentes_produtos?.map(p=>p.id_produto)??[],beneficio_itens:c.beneficio_itens??[]});setNomeImagem(c.imagem_url?"Imagem atual":"");setEtapaAtual(0);window.scrollTo({top:0,behavior:"smooth"});};
 async function salvar(e,status=form.status){e?.preventDefault();setBusy(true);setErro("");try{
 const payload={...form,status,inicio_em:form.inicio_em+":00-03:00",fim_em:form.fim_em+":00-03:00"};
 await apiRequest("/campanhas"+(form.id_campanha?"/"+form.id_campanha:""),{method:form.id_campanha?"PATCH":"POST",body:JSON.stringify(payload)});
 setForm(novo());setNomeImagem("");await carregar();if(status==="ATIVA"){window.location.assign("/restaurante/campanhas/publicadas");return;}setErro("Campanha salva.");
 }catch(e){setErro(e.message);}finally{setBusy(false);}}
 async function status(c,s){setBusy(true);setErro("");try{const produtos=c.produtos??c.campanhas_inteligentes_produtos?.map(p=>p.id_produto)??[];await apiRequest("/campanhas/"+c.id_campanha,{method:"PATCH",body:JSON.stringify({...c,status:s,produtos})});await carregar();}catch(e){setErro(e instanceof Error?e.message:"Não foi possível atualizar o status da campanha.");}finally{setBusy(false);}}
 const disponiveis=dados.produtos.filter(p=>p.disponivel&&!p.arquivado);
 const procurarProdutos=termo=>disponiveis.filter(p=>normalizarTexto(p.nome).includes(normalizarTexto(termo))).slice(0,12);
 const produtoPorId=id=>disponiveis.find(p=>p.id_produto===id);
 const avancarEtapa=()=>{if(etapaAtual===0&&(!form.titulo.trim()||!form.tipo_beneficio)){setErro("Informe o título e o benefício da campanha.");return;}if(!form.inicio_em||!form.fim_em||!form.limite_usos){setErro("Informe o período e o limite de usos da campanha.");return;}setErro("");setEtapaAtual(1);};
 if(estadoAcesso==="carregando")return <main className="min-h-screen bg-white px-5 py-10 text-app-cafe-profundo"><section className="mx-auto max-w-6xl"><p className="text-sm text-app-cinza">Carregando campanhas...</p></section></main>;
 if(estadoAcesso==="bloqueado")return (
  <main className="flex min-h-dvh items-center justify-center bg-[#fcfbfa] px-5 py-12 text-app-cafe-profundo sm:py-16">
   <section aria-labelledby="campanhas-profissional-titulo" className="w-full max-w-xl rounded-2xl border border-app-baunilha-dourada/70 bg-white p-7 shadow-[0_12px_32px_rgba(62,38,27,0.06)] sm:p-8">
    <div className="flex items-center gap-3">
     <span className="h-2 w-2 shrink-0 rounded-full bg-app-caramelo-torrado" aria-hidden="true"/>
     <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-app-caramelo-torrado">Exclusivo do plano Profissional</p>
    </div>
    <h1 id="campanhas-profissional-titulo" className="mt-5 text-3xl font-semibold tracking-tight">Campanhas inteligentes</h1>
    <p className="mt-3 text-sm leading-6 text-app-cinza">Melhore seu plano para o Profissional e crie ofertas para atrair mais clientes. Receba sugestões de campanhas e acompanhe os resultados do seu restaurante.</p>
    <div className="mt-8 flex justify-center border-t border-app-baunilha-dourada/60 pt-5">
     <Link href="/restaurante/configuracoes/planos" className="inline-flex items-center justify-center gap-2 rounded-lg bg-app-cafe-profundo px-4 py-2.5 text-center text-sm font-semibold text-white transition hover:bg-app-mocha">Conhecer o plano Profissional <span aria-hidden="true">→</span></Link>
    </div>
   </section>
  </main>
 );
 return <main className="min-h-screen bg-white px-5 py-10 text-app-cafe-profundo"><section className="mx-auto max-w-6xl">
 <h1 className="text-3xl font-semibold">Campanhas inteligentes</h1><Link href="/restaurante/configuracoes/planos">Ver planos</Link>
 {erro&&<p role="status" className="my-4 rounded-lg bg-app-creme-leve p-4">{erro}</p>}
 {estadoSugestoes==="com_dados"&&<section id="sugestoes-appono" className="my-6 rounded-xl border border-app-baunilha-dourada bg-app-creme-leve p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-app-caramelo-torrado">Análise da Appono</p><h2 className="mt-2 text-xl font-semibold">Quando sua campanha tem mais sinais de demanda</h2><p className="mt-2 text-sm text-app-cinza">Leitura dos últimos 90 dias de refeições planejadas agregadas. Não representa vendas confirmadas nem garante resultado.</p>{analise?.disponivel&&<><div className="mt-4 grid gap-3 sm:grid-cols-3"><article className="rounded-lg bg-white p-4"><p className="text-sm text-app-cinza">Refeições planejadas</p><strong className="text-2xl">{analise.refeicoes_planejadas}</strong></article><article className="rounded-lg bg-white p-4"><p className="text-sm text-app-cinza">Dias com sinais</p><strong className="text-2xl">{analise.dias_com_sinais}</strong></article><article className="rounded-lg bg-white p-4"><p className="text-sm text-app-cinza">Janelas analisadas</p><strong className="text-2xl">{analise.janelas_analisadas}</strong></article></div><div className="mt-5 grid gap-3">{analise.janelas_recomendadas?.map((janela,i)=><article className="rounded-xl border bg-white p-4" key={`${janela.dia_semana}-${janela.faixa_horario}`}><p className="text-xs font-bold uppercase tracking-[0.12em] text-app-caramelo-torrado">{i===0?"Melhor janela observada":"Janela alternativa"}</p><h3 className="mt-1 font-semibold">{janela.dia_semana} · {janela.faixa_horario}</h3><p className="mt-1 text-sm">{janela.refeicoes_planejadas} refeições planejadas em {janela.dias_observados} dia(s), média de {janela.media_refeicoes_por_dia} por dia.</p></article>)}</div></>}<div className="mt-6 border-t border-app-baunilha-dourada pt-5"><p className="text-xs font-bold uppercase tracking-[0.18em] text-app-caramelo-torrado">Sugestões da Appono</p><h2 className="mt-2 text-xl font-semibold">Escolha uma sugestão para iniciar a campanha</h2><p className="mt-2 text-sm text-app-cinza">Revise a oferta antes de salvar ou publicar.</p>{sugestoes.length?<div className="mt-4 grid gap-3">{sugestoes.map((s,i)=><article className="rounded-xl border bg-white p-4" key={i}><p className="font-medium">{s.mensagem}</p><p className="mt-1 text-sm">Base: {s.amostra?.refeicoes_planejadas} refeições planejadas em {s.amostra?.dias_observados} dia(s) comparáveis.</p><p className="mt-2 text-sm text-app-cinza">{s.limitacao}</p><button className="mt-3 rounded-lg bg-app-cafe-profundo px-4 py-2 text-sm font-semibold text-white" onClick={()=>editar({...novo(),...s.rascunho})}>Usar esta sugestão</button></article>)}</div>:<p className="mt-3 text-sm text-app-cinza">{motivoSemSugestao}</p>}</div></section>}
 {estadoSugestoes==="erro"&&<p id="sugestoes-appono" role="alert" className="my-6 text-sm text-app-cinza">{erroSug}</p>}
 <form onSubmit={e=>salvar(e,"ATIVA")} className="my-6 grid gap-4 rounded-xl border border-app-baunilha-dourada bg-app-creme-leve p-6 shadow-sm md:grid-cols-2">
 <div className="md:col-span-2"><FormStepper steps={[{title:"Oferta"},{title:"Condições e publicação"}]} currentStep={etapaAtual} onStepClick={setEtapaAtual} completedClassName="bg-app-dourado-mel text-app-creme-leve hover:bg-app-caramelo-torrado" progressClassName="bg-app-dourado-mel" /></div>
 <h2 className="text-xl md:col-span-2">{form.id_campanha?"Editar campanha":"Nova campanha"}</h2>
 {form.id_campanha&&<p className="md:col-span-2">Os resgates existentes mantêm as condições aceitas pelos clientes.</p>}
 <div className={etapaAtual===0?"contents":"hidden"}>
 <label>Título<input required maxLength={120} className={classe} value={form.titulo} onChange={e=>set("titulo",e.target.value)}/></label>
 <label>Benefício<select className={classe} value={form.tipo_beneficio} onChange={e=>set("tipo_beneficio",e.target.value)}>{tipos.map(t=><option key={t} value={t}>{label(t)}</option>)}</select></label>
 <label className="md:col-span-2">Descrição<textarea className={classe} value={form.descricao??""} onChange={e=>set("descricao",e.target.value)}/></label>
 {form.tipo_beneficio.startsWith("DESCONTO")&&<label>{form.tipo_beneficio==="DESCONTO_PERCENTUAL"?"Desconto (%)":"Desconto (R$)"}<input type="number" min=".01" step=".01" max={form.tipo_beneficio==="DESCONTO_PERCENTUAL"?100:undefined} required className={classe} value={form.valor_beneficio??""} onChange={e=>set("valor_beneficio",e.target.value)}/></label>}
 {form.tipo_beneficio==="COMBO"&&<label>Preço total do combo (R$)<input type="number" min="0" step=".01" required className={classe} value={form.preco_combo??""} onChange={e=>set("preco_combo",e.target.value)}/></label>}
 <fieldset className="rounded-lg border p-3"><legend>Produtos elegíveis</legend><p className="mb-2 text-sm text-app-cinza">Sem produtos selecionados, a oferta vale para qualquer produto.</p><input className={classe} type="search" placeholder="Buscar produto" value={buscaElegiveis} onChange={e=>setBuscaElegiveis(e.target.value)}/><div className="mt-2 flex flex-wrap gap-2">{form.produtos.map(id=>{const produto=produtoPorId(id);return produto&&<button type="button" key={id} className="rounded-full border px-3 py-1 text-sm" onClick={()=>set("produtos",form.produtos.filter(item=>item!==id))}>{produto.nome} ×</button>;})}</div><div className="mt-3 grid gap-1">{procurarProdutos(buscaElegiveis).map(p=><label key={p.id_produto} className="flex items-center gap-2"><input type="checkbox" checked={form.produtos.includes(p.id_produto)} onChange={e=>set("produtos",e.target.checked?[...form.produtos,p.id_produto]:form.produtos.filter(id=>id!==p.id_produto))}/>{p.nome}</label>)}{buscaElegiveis&&procurarProdutos(buscaElegiveis).length===0&&<p className="text-sm text-app-cinza">Nenhum produto encontrado.</p>}</div>{form.produtos.length>0&&<button type="button" className="mt-3 text-sm underline" onClick={()=>set("produtos",[])}>Aplicar a qualquer produto</button>}</fieldset>
 {!form.tipo_beneficio.startsWith("DESCONTO")&&<fieldset className="rounded-lg border p-3"><legend>{form.tipo_beneficio==="COMBO"?"Itens que o cliente deve incluir no pedido":"Itens gratuitos a entregar"}</legend><input className={classe} type="search" placeholder="Buscar produto" value={buscaBeneficios} onChange={e=>setBuscaBeneficios(e.target.value)}/><div className="mt-3 grid gap-2">{form.beneficio_itens.map(item=>{const produto=produtoPorId(item.id_produto);return produto&&<div key={item.id_produto} className="flex items-center justify-between gap-2"><span>{produto.nome}</span><span className="flex items-center gap-2"><input aria-label={"Quantidade de "+produto.nome} className="w-20 border p-2" type="number" min="1" max="100" value={item.quantidade} onChange={e=>set("beneficio_itens",[...form.beneficio_itens.filter(i=>i.id_produto!==item.id_produto),...(Number(e.target.value)>0?[{id_produto:item.id_produto,quantidade:Number(e.target.value)}]:[])])}/><button type="button" aria-label={"Remover "+produto.nome} onClick={()=>set("beneficio_itens",form.beneficio_itens.filter(i=>i.id_produto!==item.id_produto))}>×</button></span></div>;})}</div><div className="mt-3 grid gap-1">{procurarProdutos(buscaBeneficios).filter(p=>!form.beneficio_itens.some(item=>item.id_produto===p.id_produto)).map(p=><button type="button" key={p.id_produto} className="text-left text-sm underline" onClick={()=>set("beneficio_itens",[...form.beneficio_itens,{id_produto:p.id_produto,quantidade:1}])}>Adicionar {p.nome}</button>)}{buscaBeneficios&&procurarProdutos(buscaBeneficios).length===0&&<p className="text-sm text-app-cinza">Nenhum produto encontrado.</p>}</div></fieldset>}
 </div>
 <div className={etapaAtual===1?"contents":"hidden"}>
 {["inicio_em","fim_em"].map(k=><label key={k}>{k==="inicio_em"?"Início":"Fim"} (horário de Brasília)<input required type="datetime-local" className={classe} value={form[k]} onChange={e=>set(k,e.target.value)}/></label>)}
 <p className="md:col-span-2 text-sm">A contratação e o horário da reserva devem estar dentro da validade da oferta.</p>
 {[["limite_usos","Limite de usos",100000],["minimo_pessoas","Mínimo de pessoas",30],["minimo_itens","Mínimo de itens",100]].map(([k,t,m])=><label key={k}>{t}<input className={classe} type="number" min="1" max={m} required={k==="limite_usos"} value={form[k]??""} onChange={e=>set(k,e.target.value)}/></label>)}
 <div className="md:col-span-2"><p className="mb-2 text-sm font-medium">Imagem da campanha</p><div className="flex flex-col gap-4 rounded-xl border border-dashed border-app-baunilha-dourada bg-app-creme-leve/50 p-4 sm:flex-row sm:items-center">{form.imagem_url?<img src={form.imagem_url} alt="Prévia da imagem da campanha" className="h-16 w-24 rounded-lg object-cover"/>:<div className="flex h-16 w-24 items-center justify-center rounded-lg bg-white text-app-caramelo-torrado" aria-hidden="true">↑</div>}<div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{nomeImagem||"Nenhuma imagem selecionada"}</p><p className="mt-1 text-xs text-app-cinza">JPG, PNG ou WebP · até 5 MB</p></div><div className="flex items-center gap-3"><label htmlFor="imagem-campanha" className="cursor-pointer rounded-lg border border-app-baunilha-dourada bg-white px-4 py-2 text-sm font-semibold">{busy?"Enviando...":form.imagem_url?"Trocar imagem":"Selecionar imagem"}</label><input id="imagem-campanha" disabled={busy} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setNomeImagem(file.name);setBusy(true);try{set("imagem_url",await enviarImagemCardapio(file));}catch(e){setNomeImagem("");setErro(e.message);}finally{setBusy(false);}}}/>{form.imagem_url&&<button type="button" className="text-sm text-app-cinza underline" onClick={()=>{set("imagem_url","");setNomeImagem("");}}>Remover</button>}</div></div></div>
 </div>
 <div className={etapaAtual===1?"contents":"hidden"}><label className="md:col-span-2">Regras e termos<textarea className={classe} value={form.regras??""} onChange={e=>set("regras",e.target.value)}/></label></div>
 <div className="md:col-span-2"><FormStepActions currentStep={etapaAtual} totalSteps={2} onBack={()=>setEtapaAtual(etapa=>etapa-1)} onNext={avancarEtapa} isSubmitting={busy} submitLabel="Publicar ou agendar" primaryClassName="!bg-app-dourado-mel !text-app-creme-leve hover:!bg-app-caramelo-torrado" /><div className="mt-4 flex flex-wrap justify-end gap-3"><button type="button" onClick={()=>{setForm(novo());setNomeImagem("");setEtapaAtual(0);}} className="rounded-lg px-4 py-3 text-sm text-app-cinza">Limpar</button></div></div>
 </form>
 {preview&&<section className="my-6 overflow-hidden rounded-2xl border border-app-baunilha-dourada bg-white shadow-[0_12px_32px_rgba(62,38,27,0.08)]"><div className="grid md:grid-cols-[0.9fr_1.1fr]">{form.imagem_url?<img alt="Prévia da campanha" src={form.imagem_url} className="h-64 w-full object-cover md:h-full"/>:<div className="flex min-h-64 items-center justify-center bg-app-creme-leve px-8 text-center text-sm text-app-cinza">A imagem da campanha aparecerá aqui</div>}<div className="p-6 sm:p-8"><div className="flex items-center justify-between gap-4"><span className="rounded-full bg-app-creme-leve px-3 py-1 text-xs font-bold uppercase tracking-wider text-app-caramelo-torrado">Prévia para o cliente</span><button type="button" onClick={()=>setPreview(false)} className="text-sm font-semibold text-app-mocha underline underline-offset-4">Fechar</button></div><h2 className="mt-5 text-3xl font-semibold leading-tight text-app-cafe-profundo">{form.titulo||"Nome da campanha"}</h2><p className="mt-3 text-sm leading-6 text-app-cinza">{form.descricao||"A descrição da campanha aparecerá para seus clientes."}</p><div className="mt-6 rounded-xl bg-app-cafe-profundo p-4 text-app-creme-leve"><p className="text-xs font-bold uppercase tracking-wider text-app-baunilha-dourada">Benefício</p><p className="mt-1 text-xl font-semibold">{form.tipo_beneficio==="DESCONTO_PERCENTUAL"?`${form.valor_beneficio||0}% de desconto`:form.tipo_beneficio==="DESCONTO_FIXO"?`R$ ${form.valor_beneficio||0} de desconto`:label(form.tipo_beneficio)}</p></div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><p className="text-xs text-app-cinza">Válida de</p><p className="mt-1 font-semibold">{form.inicio_em?dataCampanha(`${form.inicio_em}:00-03:00`):"Defina o início"}</p></div><div><p className="text-xs text-app-cinza">Até</p><p className="mt-1 font-semibold">{form.fim_em?dataCampanha(`${form.fim_em}:00-03:00`):"Defina o término"}</p></div></div>{form.regras?<p className="mt-5 border-t border-app-baunilha-dourada/60 pt-4 text-xs leading-5 text-app-cinza">{form.regras}</p>:null}</div></div></section>}
 <section className="mt-10"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-app-caramelo-torrado">Suas campanhas</p><h2 className="mt-1 text-2xl font-semibold">Ofertas criadas</h2></div><span className="text-sm text-app-cinza">{dados.campanhas.length} {dados.campanhas.length===1?"campanha":"campanhas"}</span></div><div className="grid gap-4 lg:grid-cols-2">{dados.campanhas.map(c=><article key={c.id_campanha} className="rounded-2xl border border-app-baunilha-dourada/70 bg-white p-5 shadow-[0_8px_24px_rgba(62,38,27,0.04)]"><div className="flex items-start justify-between gap-4"><span className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${classeStatus(c.status)}`}>{label(c.status)}</span><span className="text-right text-sm text-app-cinza"><strong className="block text-app-cafe-profundo">{c.usos_confirmados}/{c.limite_usos}</strong>usos comprometidos</span></div><h3 className="mt-5 text-xl font-semibold leading-snug">{c.titulo}</h3><p className="mt-2 min-h-10 text-sm leading-5 text-app-cinza">{motivoEstado(c)}</p><div className="mt-5 grid grid-cols-2 gap-3 border-y border-app-baunilha-dourada/60 py-4 text-sm"><div><p className="text-xs text-app-cinza">Início</p><p className="mt-1 font-medium">{dataCampanha(c.inicio_em)}</p></div><div><p className="text-xs text-app-cinza">Término</p><p className="mt-1 font-medium">{dataCampanha(c.fim_em)}</p></div></div><div className="mt-5 flex flex-wrap items-center gap-3">{!["ENCERRADA","EXPIRADA"].includes(c.status)&&<><button disabled={busy} className="text-sm font-semibold underline underline-offset-4" onClick={()=>editar(c)}>Editar</button><button disabled={busy} className="text-sm font-semibold underline underline-offset-4" onClick={()=>status(c,c.status==="PAUSADA"?"ATIVA":"PAUSADA")}>{c.status==="PAUSADA"?"Retomar":"Pausar"}</button><button disabled={busy} className="text-sm text-app-cinza" onClick={()=>status(c,"ENCERRADA")}>Encerrar</button></>}<Link className="ml-auto rounded-lg bg-app-cafe-profundo px-4 py-2 text-sm font-semibold text-white" href={"/restaurante/campanhas/"+c.id_campanha}>Ver resultados</Link></div></article>)}</div>{!dados.campanhas.length&&<p className="rounded-xl border border-dashed border-app-baunilha-dourada p-6 text-sm text-app-cinza">Nenhuma campanha criada ainda.</p>}</section>
 </section></main>;
}
